export const ProductCode = {
  Other: 'other',
  Insurance: 'insurance',
  Travel: 'travel',
  Utilities: 'utilities',
  Telecom: 'telecom',
  Education: 'education',
  Banking: 'banking',
  Entertainment: 'entertainment',
  Fashion: 'fashion',
  Health: 'health',
  Food: 'food',
  Transport: 'transport',
  Books: 'books',
  Electronics: 'electronics',
  RealEstate: 'real_estate',
  Services: 'services',
  Gaming: 'gaming',
  Charity: 'charity',
  Investment: 'investment',
  Crypto: 'crypto',
};
